### ISSUE TITLE
“学宝”虚拟机调教日记（二） | Hugefiver‘s Blog

### ISSUE THREAD

**Issue by hugefiver** [hugefiver/hf_gitment#5]
https://blog.rurilove.moe/2018/04/02/3/

**Comment by Anthony-Hoo** [comment]
校友你好，请问你是否尝试过用其他的方法连进虚拟机呢，比如在自己的电脑上搭建VPN？我试过，在虚拟机通过自己的电脑代理访问网页是可行的，至少看哔哩哔哩没问题。至于你所说的网段隔离，我和同学都没遇到过，不知道具体是一种怎样的情形？

**Comment by hugefiver** [comment]
@Anthony-Hoo 抱歉，这么久才回复，一直没看到有评论。可能你早已为这些问题找到了答案。
1. 其他方法进入虚拟机：我本人只试过使用微软自家的`RDP`协议。不过有大佬通过学宝VNC协议连接之后提取日志文件来达到VNC连接的目的。在我告诉他rdp的事情之后他也放弃了VNC，毕竟rdp确实很好用。
2. 虚拟机通过代理浏览网页：本文讲的就是这个。我使用的是v2ray来提供代理。因为没必要使用VPN，我们只是需要代理而已。另外现在基本证实了17级的同学的虚拟机可以直接访问外网的，你如果是17级或者认识17级的可以试试。（不过不要传播太广，这个bug被修复就没办法玩了）。而且我说看不了片主要还是性能问题，和网速无关。
3. 网段隔离的话，出现在16级之前。倒不如说17级才是特别的。
